CREATE TABLE member (
    email VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    image_url VARCHAR(1000)
);

CREATE TABLE wish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id VARCHAR(255) NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE wish
    ADD CONSTRAINT fk_wish_member_id_ref_member_email
    FOREIGN KEY (member_id)
    REFERENCES member (email);

ALTER TABLE wish
    ADD CONSTRAINT fk_wish_product_id_ref_product_id
    FOREIGN KEY (product_id)
    REFERENCES product (id);
