server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: spring-gift
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    name: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

kakao:
  client-id: ${KAKAO_CLIENT_ID:your_client_id_here}
  redirect-uri: http://localhost:8080/redirect
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com