# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL initialization
spring.h2.console.settings.trace=true
spring.sql.init.mode=embedded
spring.sql.init.data-locations=classpath:sql/init-db.sql,classpath:sql/testing-dataset.sql


## JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Error handling
server.error.path=/error
server.error.include-stacktrace=always

# Logging
logging.level.org.springframework.web=DEBUG