spring.application.name=spring-gift
spring.config.import= optional:file:.env[.properties],optional:file:.env.local[.properties]

# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL initialization
spring.h2.console.settings.trace=true
spring.sql.init.mode=embedded
spring.sql.init.data-locations=classpath:sql/init-db.sql,classpath:sql/init-dataset.sql,classpath:sql/testing-dataset.sql


## JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Error handling
server.error.path=/error
server.error.include-stacktrace=always

# Logging
logging.level.org.springframework.web=DEBUG

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=600s

# jwt
gift.jwt.secret=${JWT_SECRET}
gift.jwt.expiration=${JWT_EXPIRATION::3600}
gift.jwt.issuer=spring-gift

gift.base-url=${SERVER_URL::http://localhost}:${SERVER_PORT::8080}

# OAuth2 configuration
gift.oauth.redirect-uri=${SERVER_URL::http://localhost}:${SERVER_PORT::8080}/api/auth/oauth2
gift.oauth.provider.kakao.baseurl=https://kauth.kakao.com
gift.oauth.provider.kakao.rest-api-key=${KAKAO_OAUTH_KEY}

# service
gift.service.kakao.message.url=https://kapi.kakao.com/v2/api/talk/memo/send


gift.cors.allowed-origins=${SERVER_URL::http://localhost}:${SERVER_PORT::8080}