spring.application.name=spring-gift
#h2-console
spring.h2.console.enabled=true
#db url, MySQL Dialect
spring.datasource.url=jdbc:h2:mem:test;
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
#secretKey
app.jwt.secret-key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
#JPA Query Log
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#KaKao Authorization_code
custom.kakao-auth-key=YeMj_XeK3LDcWLxTl1cO9YkvZV-dit5o63e1vR4nIzLtpi7l0Gn_sgAAAAQKFxafAAABmDtvakvDukuslKNZWg
#Kakao REST-api key
custom.kakao-client-id=8e505163012e6c40949e61818ee9a17d
#Kakao Redirect URI
custom.kakao-redirect=http://localhost:8080