spring.application.name=spring-gift
#h2-console
spring.h2.console.enabled=true
#db url, MySQL Dialect
spring.datasource.url=jdbc:h2:mem:test;
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
#secretKey
app.jwt.secret-key=${APP_JWT_SECRET_KEY:}
#JPA Query Log
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#Kakao REST-api key
custom.kakao-client-id=${CUSTOM_KAKAO_CLIENT_ID:}
#Kakao Redirect URI
custom.kakao-redirect=${CUSTOM_KAKAO_REDIRECT:}
#Kakao Token Auth Serverr
custom.kakao-auth-server=${CUSTOM_KAKAO_AUTH_SERVER:https://kauth.kakao.com/oauth/token}
#Kakao Message Send URL
custom.kakao-sendTo-myself=${CUSTOM_KAKAO_SENDTO_MYSELF:https://kapi.kakao.com/v2/api/talk/memo/default/send}
#Kakao User Info URL
custom.kakao-user-info=${CUSTOM_KAKAO_USER_INFO:https://kapi.kakao.com/v2/user/me}