spring.application.name=spring-gift

spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

jwt.secret.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

kakao.client.id=${KAKAO_CLIENT_ID}
kakao.redirect.uri=${KAKAO_REDIRECT_URI}

kakao.api.url.auth=https://kauth.kakao.com
kakao.api.url.api=https://kapi.kakao.com