kakao.client-id=0090f2a7cd7b44c949fc8a206d317816
kakao.redirect-url=http://localhost:8080/callback

server.port=443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=105700
