jwt:
  secret: ${jwt.secret}
  expiration_ms: 3600000

spring:
  config:
    import: optional:application-secret.yml
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${kakao.redirect-uri}
            client-id: ${kakao.client-id}
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token