kakao.client_id=${KAKAO_CLIENT_ID}
kakao.redirect_uri = ${KAKAO_REDIRECT_URI}
kakao.token_uri=https://kauth.kakao.com/oauth/token
kakao.user_info_uri=https://kapi.kakao.com/v2/user/me
kakao.check_agree_uri=https://kapi.kakao.com/v2/user/scopes
kakao.oauth_uri=https://kauth.kakao.com/oauth/authorize
kakao.talk_uri=https://kapi.kakao.com/v2/api/talk/memo/default/send