spring:
  application:
    name: spring-gift

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: never
      schema-locations: classpath:Schema.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  expiration: 3600000 #1시간(ms단위)

kakao:
  client-id: 71ad85ed78c82915ffeb529b00e34988
  redirect-uri: http://52.78.57.212:8080/callback
  link-url: http://52.78.57.212:8080
  button-title: 주문 확인
