spring:
  application:
    name: spring-gift
  datasource:
    driver-class-name: org.h2.Driver
    url: ${KAKAO_TECH_CAMPUS_DB}
    username: ${KAKAO_TECH_CAMPUS_DB_USERNAME}
    password: ${KAKAO_TECH_CAMPUS_DB_PASSWORD}
  thymeleaf:
    prefix: classpath:/templates/
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt-secret-key: ${JWT_SECRET_KEY}
jwt-access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}

kakao-client-id: ${KAKAO_TECH_CAMPUS_CLIENT_ID}
kakao-redirect-url: ${KAKAO_TECH_CAMPUS_REDIRECT_URL}

server:
  port: 8080
