spring.application.name=spring-gift
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.h2.console.enabled=true
spring.datasource.password=
spring.datasource.username=sa
spring.sql.init.mode = always
spring.h2.console.settings.web-allow-others=true
spring.profiles.active=test
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql
jwt.secret=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Kakao API
kakao.client-id=${KAKAO_REST_API_KEY}
kakao.redirect-uri=http://54.91.233.77:8080/oauth/kakao/callback

# Kakao OAuth
kakao.auth.host=https://kauth.kakao.com
kakao.api.host=https://kapi.kakao.com
