spring:
  application:
    name: spring-gift
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret: kakaoTechCampus2025KNUFightingAzaAzaAza
  access-token-validity: 1800 # 단위: s