create table products
(
    id        bigint       generated by default as identity,
    price     integer      not null,
    name      varchar(15)  not null,
    image_url varchar(255) not null,
    primary key (id)
);

create table users
(
    id       bigint       generated by default as identity,
    email    varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

create table wishes
(
    id         bigint  generated by default as identity,
    user_id    bigint  not null,
    product_id bigint  not null,
    quantity   integer not null,
    primary key (id)
);

create table options
(
    id         bigint generated by default as identity,
    product_id bigint       not null,
    name       varchar(255) not null,
    quantity   integer      not null,
    primary key (id),
    unique (product_id, name)
);

alter table if exists wishes
    add constraint fk_wish_user_id_ref_user_id
    foreign key (user_id)
    references users;

alter table if exists wishes
    add constraint fk_wish_product_id_ref_product_id
    foreign key (product_id)
    references products;

alter table if exists options
    add constraint fk_option_product_id_ref_product_id
    foreign key (product_id)
    references products;